<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="description"
      content="A layout example that shows off 6 beautiful cats."
    />
    <title>Photo Gallery &ndash; Layout Examples &ndash; Pure</title>
    <link rel="stylesheet" href="/css/pure-min.css" />
    <link rel="stylesheet" href="/css/grids-responsive-min.css" />
    <link rel="stylesheet" href="/css/styles.css" />
  </head>
  <body>
    <div>
      <div class="header">
        <div class="pure-menu pure-menu-horizontal">
          <a class="pure-menu-heading" href="index">Cats!</a>

          <ul class="pure-menu-list">
            <li class="pure-menu-item pure-menu-selected">
              <a href="index" class="pure-menu-link">Home</a>
            </li>
            <li class="pure-menu-item">
              <a href="details" class="pure-menu-link">Details</a>
            </li>
            <li class="pure-menu-item">
              <a href="all" class="pure-menu-link">About</a>
            </li>
            <li class="pure-menu-item">
              <a href="createForm" class="pure-menu-link">Create Cat</a>
            </li>

            
          </ul>
        </div>
      </div>

      <div class="pure-g">
        <div class="photo-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
          <a href="/images/Aegean.jpg">
            <img
              src="/images/Aegean.jpg"
              alt="Aegean"
            />
          </a>

          <aside class="photo-box-caption">
            <span
              >Breed: Aegean</a
              ></span
            >
          </aside>
        </div>

        <div class="text-box pure-u-1 pure-u-md-1-2 pure-u-lg-2-3">
          <div class="l-box">
            <h1 class="text-box-head">Cat photos!</h1>
            <p class="text-box-subhead">
              A collection of beautiful cat photos.
            </p>
          </div>
        </div>

        <div class="photo-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
          <a
            href="/images/Chartreux.jpg"
          >
            <img
            src="/images/Chartreux.jpg"
              alt="Chartreux"
            />
          </a>

          <aside class="photo-box-caption">
            <span>Breed: Chartreux</span>
          </aside>
        </div>

        <div class="photo-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
          <a href="/images/Munchkin.png">
            <img
              src="/images/Munchkin.png"
              alt="Munchkin"
            />
          </a>

          <aside class="photo-box-caption">
            <span>Breed: Munchkin</span>
          </aside>
        </div>

        <div class="photo-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
          <a href="/images/Siamese.jpg">
            <img
              src="/images/Siamese.jpg">"
              alt="Siamese"
            />
          </a>

          <aside class="photo-box-caption">
            <span>Breed: Siamese
            </span>
          </aside>
        </div>
       
        <div class="photo-box photo-box-thin pure-u-1 pure-u-md-2-3">
          <a  href="/images/TurkishAngora.jpg">"
            <img
              src="/images/TurkishAngora.jpg"
              alt="Turkish Angora"
            />
          </a>

          <aside class="photo-box-caption">
            <span>
               <a href="/images/Tabby.jpg">Breed: Turkish Angora</a>
            </span>
          </aside>
        </div>

        <div class="photo-box pure-u-1 pure-u-md-1-3">
          <a href="/images/Tabby.jpg">
            <img
              src="/images/Tabby.jpg"
              alt="Tabby"
            />
          </a>

          <aside class="photo-box-caption">
            <span>
               <a href="/images/Tabby.jpg">Breed: Tabby</a>
            </span>
          </aside>
        </div>


        

   

        <div class="pure-u-1">
          <div class="l-box">
            

            
          </div>
        </div>
      </div>

      <div class="footer">
        View the source of this layout to learn more. Made by Brian Granados with https://pure-css.github.io/
      </div>
    </div>
  </body>
</html>
